# Generated by Django 6.0.3 on 2026-03-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_ban', models.CharField(max_length=20, unique=True)),
                ('so_ghe', models.IntegerField()),
                ('trang_thai', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ban',
            },
        ),
        migrations.CreateModel(
            name='LoaiMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loai_mon',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=150)),
                ('vi_tri', models.CharField(blank=True, max_length=50, null=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('ngay_vao_lam', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nhan_vien',
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_don', models.CharField(blank=True, max_length=50, null=True)),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, null=True)),
                ('ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ban')),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nhanvien')),
            ],
            options={
                'db_table': 'don_hang',
            },
        ),
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=200)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('gia_ban', models.DecimalField(decimal_places=0, max_digits=18)),
                ('hinh_anh', models.CharField(blank=True, max_length=255, null=True)),
                ('trang_thai_ban', models.BooleanField(blank=True, null=True)),
                ('loai_mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loaimon')),
            ],
            options={
                'db_table': 'mon_an',
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.CharField(blank=True, max_length=100, null=True)),
                ('diem_danh_gia', models.IntegerField(blank=True, null=True)),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, null=True)),
                ('mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.monan')),
            ],
            options={
                'db_table': 'danh_gia',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia_luc_ban', models.DecimalField(decimal_places=0, max_digits=18)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donhang')),
                ('mon_an', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.monan')),
            ],
            options={
                'db_table': 'chi_tiet_don_hang',
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong_thuc', models.CharField(blank=True, max_length=50, null=True)),
                ('trang_thai_thanh_toan', models.CharField(blank=True, max_length=50, null=True)),
                ('thoi_gian_thanh_toan', models.DateTimeField(blank=True, null=True)),
                ('don_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.donhang')),
            ],
            options={
                'db_table': 'thanh_toan',
            },
        ),
    ]
