# Generated by Django 6.0.3 on 2026-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Vietnamese_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Vietnamese_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Vietnamese_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Vietnamese_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_ban', models.CharField(db_collation='Vietnamese_CI_AS', max_length=20, unique=True)),
                ('so_ghe', models.IntegerField()),
                ('trang_thai', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ban',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia_luc_ban', models.DecimalField(decimal_places=0, max_digits=18)),
                ('ghi_chu', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'chi_tiet_don_hang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=100, null=True)),
                ('diem_danh_gia', models.IntegerField(blank=True, null=True)),
                ('noi_dung', models.TextField(blank=True, db_collation='Vietnamese_CI_AS', null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'danh_gia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Vietnamese_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Vietnamese_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Vietnamese_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Vietnamese_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Vietnamese_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Vietnamese_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Vietnamese_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Vietnamese_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Vietnamese_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_don', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=50, null=True)),
                ('tong_tien', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('thoi_gian_tao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'don_hang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoaiMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(db_collation='Vietnamese_CI_AS', max_length=100)),
                ('mo_ta', models.TextField(blank=True, db_collation='Vietnamese_CI_AS', null=True)),
            ],
            options={
                'db_table': 'loai_mon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(db_collation='Vietnamese_CI_AS', max_length=200)),
                ('mo_ta', models.TextField(blank=True, db_collation='Vietnamese_CI_AS', null=True)),
                ('gia_ban', models.DecimalField(decimal_places=0, max_digits=18)),
                ('hinh_anh', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=255, null=True)),
                ('trang_thai_ban', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mon_an',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(db_collation='Vietnamese_CI_AS', max_length=150)),
                ('vi_tri', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=50, null=True)),
                ('so_dien_thoai', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=100, null=True)),
                ('ngay_vao_lam', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nhan_vien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong_thuc', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=50, null=True)),
                ('trang_thai_thanh_toan', models.CharField(blank=True, db_collation='Vietnamese_CI_AS', max_length=50, null=True)),
                ('thoi_gian_thanh_toan', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'thanh_toan',
                'managed': False,
            },
        ),
    ]
