# Generated by Django 6.0.3 on 2026-05-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('loai_giam', models.CharField(choices=[('TienMat', 'Giảm thẳng tiền (VNĐ)'), ('PhanTram', 'Giảm theo phần trăm (%)')], default='TienMat', max_length=20, verbose_name='Loại giảm')),
                ('gia_tri', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Giá trị giảm (VNĐ hoặc %)')),
                ('so_luong_gioi_han', models.IntegerField(help_text='Nhập số lần mã này có thể được sử dụng', verbose_name='Số lượng tối đa')),
                ('so_luong_da_dung', models.IntegerField(default=0, verbose_name='Số lượng đã dùng')),
                ('ngay_het_han', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('kich_hoat', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Quản lý Mã giảm giá',
                'db_table': 'voucher',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='donhang',
            name='tien_giam_gia',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True, verbose_name='Tiền được giảm'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.voucher', verbose_name='Voucher áp dụng'),
        ),
    ]
