# Generated by Django 6.0.3 on 2026-03-30 17:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ban',
            options={'managed': False, 'verbose_name': 'Bàn', 'verbose_name_plural': 'Quản lý Bàn'},
        ),
        migrations.AlterModelOptions(
            name='chitietdonhang',
            options={'managed': False, 'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Quản lý Chi tiết đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='danhgia',
            options={'managed': False, 'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Quản lý Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='donhang',
            options={'managed': False, 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Quản lý Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='loaimon',
            options={'managed': False, 'verbose_name': 'Loại món', 'verbose_name_plural': 'Quản lý Loại món'},
        ),
        migrations.AlterModelOptions(
            name='monan',
            options={'managed': False, 'verbose_name': 'Món ăn', 'verbose_name_plural': 'Quản lý Món ăn'},
        ),
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'managed': False, 'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Quản lý Nhân viên'},
        ),
        migrations.AlterModelOptions(
            name='thanhtoan',
            options={'managed': False, 'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Quản lý Thanh toán'},
        ),
        migrations.AddField(
            model_name='datban',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản khách đặt'),
        ),
        migrations.AlterField(
            model_name='datban',
            name='ban',
            field=models.ForeignKey(blank=True, db_column='ban_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ban', verbose_name='Bàn được xếp'),
        ),
        migrations.AlterField(
            model_name='datban',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 30, 17, 53, 9, 114093, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datban',
            name='trang_thai',
            field=models.CharField(default='ChoXacNhan', max_length=50, verbose_name='Trạng thái'),
        ),
    ]
