# Generated by Django 6.0.3 on 2026-04-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_donhang_khach_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.khachhang'),
        ),
    ]
