# Generated by Django 6.0.3 on 2026-05-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_voucher_donhang_tien_giam_gia_donhang_voucher'),
        ('core', '0004_profile_diem_tich_luy'),
        ('core', '0006_alter_donhang_khach_hang_profile_hang_thanh_vien_and_more'),
    ]

    operations = [
    ]
