# Generated by Django 6.0.3 on 2026-05-14 05:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260514_1238'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donhang',
            options={'managed': True, 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Quản lý Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Hồ sơ khách hàng', 'verbose_name_plural': 'Quản lý Hồ sơ'},
        ),
        migrations.AddField(
            model_name='profile',
            name='hang_thanh_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.hangthanhvien', verbose_name='Hạng thành viên'),
        ),
        migrations.AlterField(
            model_name='datban',
            name='so_nguoi',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số người'),
        ),
        migrations.AlterField(
            model_name='datban',
            name='tong_tien_coc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiền cọc'),
        ),
        migrations.AlterField(
            model_name='datban',
            name='trang_thai',
            field=models.CharField(choices=[('ChoXacNhan', 'Chờ xác nhận'), ('DaXacNhan', 'Đã xác nhận'), ('HoanThanh', 'Khách đã đến (Hoàn thành)'), ('DaHuy', 'Đã hủy')], default='ChoXacNhan', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='datban',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản khách'),
        ),
        migrations.AlterField(
            model_name='hangthanhvien',
            name='diem_toi_thieu',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm tối thiểu'),
        ),
        migrations.AlterField(
            model_name='hangthanhvien',
            name='phan_tram_giam_gia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Giảm giá'),
        ),
        migrations.AlterField(
            model_name='hangthanhvien',
            name='ten_hang',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên hạng'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diem_tich_luy',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm tích lũy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='gia_tri',
            field=models.DecimalField(decimal_places=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá trị giảm (VNĐ hoặc %)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='so_luong_da_dung',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng đã dùng'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='so_luong_gioi_han',
            field=models.IntegerField(help_text='Phải lớn hơn 0', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng tối đa'),
        ),
    ]
