# Generated by Django 6.0.3 on 2026-05-14 06:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_donhang_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ban', verbose_name='Bàn'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='nhan_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.nhanvien', verbose_name='Nhân viên tạo'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Thời gian tạo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donhang',
            name='tien_giam_gia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiền được giảm'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng tiền gốc'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai_don',
            field=models.CharField(choices=[('ChoXacNhan', 'Chờ xác nhận'), ('DangChuanBi', 'Đang chuẩn bị'), ('HoanThanh', 'Hoàn thành'), ('DaHuy', 'Đã hủy')], default='ChoXacNhan', max_length=50, verbose_name='Trạng thái đơn'),
        ),
    ]
