# Generated by Django 6.0.3 on 2026-04-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangThanhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hang', models.CharField(max_length=50)),
                ('phan_tram_giam_gia', models.IntegerField(blank=True, default=0, null=True)),
                ('diem_toi_thieu', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Hạng thành viên',
                'verbose_name_plural': 'Quản lý Hạng thành viên',
                'db_table': 'hang_thanh_vien',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='donhang',
            options={'managed': True, 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Quản lý Đơn hàng'},
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=20, unique=True)),
                ('diem_tich_luy', models.IntegerField(blank=True, default=0, null=True)),
                ('hang_thanh_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.hangthanhvien')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Quản lý Khách hàng',
                'db_table': 'khach_hang',
                'managed': True,
            },
        ),
    ]
