# Generated by Django 6.0.3 on 2026-04-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hangthanhvien_alter_donhang_options_khachhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='ban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ban'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.khachhang'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='nhan_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.nhanvien'),
        ),
    ]
