# Generated by Django 6.0.3 on 2026-04-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donhang_ban_donhang_khach_hang_donhang_nhan_vien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='khach_hang',
        ),
    ]
