# Generated by Django 6.0.3 on 2026-04-16 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donhang_khach_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hang_thanh_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.hangthanhvien'),
        ),
        migrations.DeleteModel(
            name='KhachHang',
        ),
    ]
